server:
  port: 7002

eureka:
  instance:
    hostname: eureka7002.com    #localhost     #eureka服务端的实例名称,单机版的时候用这个，因为唯一
  client:
    register-with-eureka: false #false表示不向注册中心注册自己。因为eureka默认会把所有的服务都注册进来。
    fetch-registry: false       #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url:
      # defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/ #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址（单机）
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7003.com:7003/eureka/ #集群
  server:
      #eviction-interval-timer-in-ms: 4000 # 设置清无效节点时间间隔（单位：毫秒 默认是60*1000）
      #enable-self-preservation: false   #禁用eureka的自我保护机制，但一般不推荐
